---
name: Update latest tag for every new latest release

"on":
  release:
    types:
      - 'released'

jobs:
  update_latest_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check if the latest release
        id: check_latest_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest_release=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
          echo "Latest release: $latest_release"
          echo "Current release: ${{ github.ref }}"
          if [[ "refs/tags/$latest_release" == "${{ github.ref }}" ]]; then
            echo "is_latest=true" >> $GITHUB_OUTPUT
          else
            echo "is_latest=false" >> $GITHUB_OUTPUT
          fi

      - name: Update latest tag
        if: steps.check_latest_release.outputs.is_latest == 'true'
        uses: EndBug/latest-tag@latest
        with:
          ref: latest
          description: Latest tag
          force-branch: true

      - name: Upload release asset
        if: steps.check_latest_release.outputs.is_latest == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: LICENSE
          token: ${{ secrets.GITHUB_TOKEN }}
